version: '2.1'
services:
  eureka-server:
    build:
      context: ../app-eureka-server
      dockerfile: Dockerfile
    image: docker-eureka-server-image
    container_name: docker-eureka-server-container
    ports:
    - 8000:8000
    networks:
    - my-network1
  app-config-server:
    build:
      context: ../app-config-server
      dockerfile: Dockerfile
    depends_on:
      eureka-server:
        condition: service_healthy
    image: docker-app-config-server-image
    container_name: docker-app-config-server-container
    ports:
    - 8040:8040
    networks:
    - my-network1
  app-config-client:
    build:
      context: ../app-config-client
      dockerfile: Dockerfile
    depends_on:
      app-config-server:
        condition: service_healthy
    image: docker-app-config-client-image
    container_name: docker-app-config-client-container
    ports:
    - 8050:8050
    networks:
    - my-network1
networks:
  my-network1:
    name: app-bridge-1