spring:
  application:
    name: app-config-client
server:
  port: 8050
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  instance:
    preferIpAddress: true